[package]
name = "chutoro-providers-dense"
version = "0.1.0"
edition = "2024"

[dependencies]
[dependencies.chutoro-core]
version = "0.1.0"
path = "../../chutoro-core"
default-features = false
features = ["skeleton"]

[dev-dependencies]
rstest = "0.26"
