[package]
name = "chutoro-test-support"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["registry"] }
